site_name: CommonRoad Route Planner

theme:
  name: readthedocs
  logo: assets/commonroad_white150.png

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            show_root_heading: false
            heading_level: 3
            show_module_names: False
  - search

nav:
  - Introduction:
    - "Introduction": index.md

  - Examples:
    - "Minimal Usage": minimal_example.md
    - "Overall Usage": example.md
    - "Planning in Frenet Frame": frenet_example.md

  - Basic API Reference:
      - "Route Planner": route_planner.md
      - "Route Generator": route_generator.md
      - "Route": route.md

  - Frenet Frame Planning:
      - "Tools": frenet.md

  - Route Generation:
      - "Route Generation via Strategy Pattern": route_generation.md

  - Lane Changing:
      - "Lane Changing via Handlers and Methods": lane_changing.md
