site_name: CommonRoad Route Planner

theme:
  name: readthedocs
  logo: assets/commonroad_white150.png

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
  - search

nav:
  - Introduction: index.md

  - Examples:
    - "Minimal Usage": minimal_example.md
    - "Overall Usage": example.md
    - "Planning in Frenet Frame": frenet_example.md

  - Basic API Reference:
      - "Route Planner": route_planner.md
      - "Route Generator": route_generator.md
      - "Route": route.md

  - Frenet Frame Planning:
      - "Route Extendor": route_generator.md
      - "Route Slice": route_slice.md

  - Route Generation:
      - "Route Generation via Strategy Pattern": route_generation_strategy.md


  - Lane Changing:
      - "Different Methods for Lane Changing": lane_changing.md


