site_name: CommonRoad ReferencePath Planner

theme:
  name: material
  logo: assets/commonroad_white150.png

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            show_root_heading: false
            heading_level: 3
            show_module_names: False
  - search

nav:
  - Introduction:
    - "Introduction": index.md

  - Examples:
    - "Fast API": fapi_usage.md
    - "Minimal Usage": minimal_example.md
    - "Overall Usage": example.md
    - "Planning in Frenet Frame": frenet_example.md


  - Fast API Reference:
      - "Fast API": fast_api.md

  - Basic API Reference:
      - "Route Planner": route_planner.md
      - "Lanelet Sequence": lanelet_sequence.md
      - "Reference Path Planner": reference_path_planner.md
      - "Reference Path": reference_path.md


  - Frenet Frame Planning:
      - "Tools": frenet.md

  - Path Generation:
      - "Path Generation via Strategy Pattern": path_generation.md

  - Lane Changing:
      - "Lane Changing via Handlers and Methods": lane_changing.md
